# Generated by Django 5.2.4 on 2025-07-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_totalgastado_cursocomprado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('Programacion', 'Desarrollo web'), ('Desarrollo movil', 'Ciberseguridad'), ('Diseño UI/UX', 'Testing')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
