# Generated by Django 5.2.4 on 2025-07-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_curso_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('Programacion', 'Programacion'), ('Desarrollo web', 'Desarrollo web'), ('Desarrollo movil', 'Desarrollo movil'), ('Ciberseguridad', 'Ciberseguridad'), ('Diseño UI/UX', 'Diseño UI/UX'), ('Testing', 'Testing')], max_length=100),
        ),
    ]
