# Generated by Django 5.2.4 on 2025-07-21 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_curso_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulo', to='cursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='VideoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='cursos.modulo')),
            ],
        ),
    ]
