# Generated by Django 5.2.4 on 2025-07-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_modulo_videomodulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodulo',
            name='video',
        ),
    ]
