# Generated by Django 5.2.4 on 2025-07-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_remove_videomodulo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodulo',
            name='video_url',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
