# Generated by Django 5.2.5 on 2025-08-18 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_curso_fecha_fin_curso_fecha_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursocomprado',
            options={'verbose_name': 'Alumnos inscritos', 'verbose_name_plural': 'alumnos inscritos'},
        ),
        migrations.AlterModelOptions(
            name='cursopreregistro',
            options={'verbose_name': 'Pre-registro de Curso', 'verbose_name_plural': 'Pre-registros de Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='maestro',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Maestro'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
    ]
