# Generated by Django 3.2 on 2025-08-18 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0011_alter_cursocomprado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='maestro',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'maestro'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
    ]
