# Generated by Django 5.2.5 on 2025-08-19 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_alter_curso_maestro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('archivo', models.FileField(upload_to='recursos/')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word'), ('ppt', 'PowerPoint'), ('img', 'Imagen'), ('otro', 'Otro')], default='otro', max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='cursos.curso')),
            ],
        ),
    ]
